name: 'NativeIrisApiEngineBinding'
description: 'Bindings to IrisApiEngine'

output: 'lib/src/bindings/gen/native_iris_api_engine_bindings.dart'

headers:
  entry-points:
    - 'tmp_ffi_gen_include/iris_rtm_c_api.h'
  include-directives:
    - 'tmp_ffi_gen_include/iris_rtm_c_api.h'

preamble: |
  // ignore_for_file: camel_case_types, non_constant_identifier_names

llvm-path:
  - '/opt/homebrew/opt/llvm@15'